/**
 * @packageDocumentation
 * @module api.functional
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";

/**
 * @controller AppController.ping
 * @path GET /ping
 * @accessor api.functional.ping
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function ping(connection: IConnection): Promise<ping.Output> {
  return PlainFetcher.fetch(connection, {
    ...ping.METADATA,
    template: ping.METADATA.path,
    path: ping.path(),
  });
}
export namespace ping {
  export type Output = string;

  export const METADATA = {
    method: "GET",
    path: "/ping",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/ping";
}
